# Generated by Django 4.0.4 on 2022-04-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cash_sum',
            field=models.IntegerField(default=0, verbose_name='Средств в наличии'),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('type_operation', 'name')},
        ),
    ]
