# Generated by Django 4.0.4 on 2022-04-24 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportOfDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя отчета')),
                ('start_date', models.DateField(verbose_name='Дата начала периода')),
                ('end_date', models.DateField(verbose_name='Дата окончания периода')),
                ('total', models.IntegerField(default=0, verbose_name='Итого по периоду')),
                ('income', models.PositiveIntegerField(default=0, verbose_name='Доходы по периоду')),
                ('expenses', models.PositiveIntegerField(default=0, verbose_name='Расходы по периоду')),
                ('articles', models.ManyToManyField(help_text='Оставить пустым, если нужно посчитать для всех статей', related_name='report', to='dds.article', verbose_name='Статьи для рассчета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
    ]
